[package]
name = "secp256r1_hash"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = { version = "0.21", features = ["invocation"] }
sha2 = "0.10"
rand = "0.8"
rand_chacha = "0.3"
curve25519-dalek = { version = "4.1", features = ["serde", "rand_core"] }